#!/bin/bash
set -e
export PICO_SDK_PATH=/home/mo/tempd/pico/pico-sdk-2.1.0/
cd build
make
# cp -a test.uf2 /media/mo/RPI-RP2/
/home/mo/tempd/pico/openocd/usr/local/bin/openocd -f /home/mo/tempd/pico/openocd/usr/local/share/openocd/scripts/interface/picoprobe.cfg -f /home/mo/tempd/pico/openocd/usr/local/share/openocd/scripts/target/rp2040.cfg -c "program main.elf verify reset exit"
