#!/bin/bash
set -e
export PICO_SDK_PATH=/home/mo/tempd/pico/pico-sdk-2.1.0/
echo \#define FWVERSION \"`date +%s ; date -Iseconds`\" >version.h
pushd build
cmake ..
make
# cp -a test.uf2 /media/mo/RPI-RP2/
# /home/mo/tempd/pico/openocd/usr/local/bin/openocd -f /home/mo/tempd/pico/openocd/usr/local/share/openocd/scripts/interface/picoprobe.cfg -f /home/mo/tempd/pico/openocd/usr/local/share/openocd/scripts/target/rp2040.cfg -c "program main.elf verify reset exit"
cd ../../bhbl-pico
make
./sign ../firmware-pico/build/main.bin
./upload /dev/ttyUSB0 ../firmware-pico/build/main.bin signature.bin
popd
