#!/bin/bash
set -e
cd build
cmake ..
make
# cp -a test.uf2 /media/mo/RPI-RP2/
# /home/mo/tempd/pico/openocd/usr/local/bin/openocd -f /home/mo/tempd/pico/openocd/usr/local/share/openocd/scripts/interface/picoprobe.cfg -f /home/mo/tempd/pico/openocd/usr/local/share/openocd/scripts/target/rp2040.cfg -c "program main.elf verify reset exit"

../../bhbl-pico/upload /dev/ttyUSB0 main.bin
